---
- name: Get SQL from Git and execute on SQL Server
  hosts: localhost
  connection: local  # Use local connection
  tasks:
    - name: Install Git (if not already installed)
      ansible.builtin.apt:
        name: git
        state: present
      become: yes

    - name: Clone the Git repository
      ansible.builtin.git:
        repo: 'https://github.com/mastronardif/myansible.git'
        dest: '/tmp/sql-scripts'
        version: 'main'  # Replace with the branch you need (e.g., main or master)
      become: yes

    - name: Read the SQL file from Git repository
      ansible.builtin.slurp:
        src: '/tmp/sql-scripts/sql/test.sql'  # Replace with the actual SQL file name
      register: sql_file_content

    - name: Execute SQL script on SQL Server
      ansible.builtin.shell: |
        echo "{{ sql_file_content.content | b64decode }}" | sqlcmd -S 192.168.1.184,1433 -U sa -P admin -d master
      environment:
        LANG: en_US.UTF-8
      become: yes
